### ISSUE TITLE
Can't load confounds on friends bold data

### ISSUE THREAD

**Issue by FrancoisPgm** [SIMEXP/load_confounds#69]
Following the readme example, I tried loading the confounds with :

`confounds = Params36().load(file_path)`

with `file_path = "/home/fpaugam/projects/rrg-pbellec/datasets/cneuromod_new/friends/sub-01/ses-001/func/sub-01_ses-001_task-s01e01a_bold.nii.gz"`, so the tsv file is the same directory. 
However I get the following error :

```Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/lustre03/project/6003287/fpaugam/fmri-generator/benchmark/env/lib/python3.6/site-packages/load_confounds/parser.py", line 294, in load
    conf, col = self._load_single(file)
  File "/lustre03/project/6003287/fpaugam/fmri-generator/benchmark/env/lib/python3.6/site-packages/load_confounds/parser.py", line 311, in _load_single
    confounds_raw = _confounds2df(confounds_raw)
  File "/lustre03/project/6003287/fpaugam/fmri-generator/benchmark/env/lib/python3.6/site-packages/load_confounds/parser.py", line 154, in _confounds2df
    suffix = "_space-" + confounds_raw.split("space-")[1]
IndexError: list index out of range
```

It seems that it is looking for a "_space-" suffix in the file path but my file has no such suffix.

**Comment by FrancoisPgm** [comment]
Also, if I use directly the tsv file, I get either :
```
  File "/lustre03/project/6003287/fpaugam/fmri-generator/benchmark/env/lib/python3.6/site-packages/load_confounds/parser.py", line 38, in _check_params
    f"The parameter {par} cannot be found in the available confounds. You may want to use a different denoising strategy'"
ValueError: The parameter trans_x cannot be found in the available confounds. You may want to use a different denoising strategy'
```
for Params9 to Params36, or :
```
  File "/lustre03/project/6003287/fpaugam/fmri-generator/benchmark/env/lib/python3.6/site-packages/load_confounds/parser.py", line 54, in _find_confounds
    raise ValueError(f"could not find any confound with the key {key}")
ValueError: could not find any confound with the key cosine
```
for Params2.

**Comment by pbellec** [comment]
This is likely related to this issue https://github.com/SIMEXP/load_confounds/issues/57

We've preprocessed the 2020-beta release with the latest version of fmriprep, and the key may have changed.
